name: "Notify"
description: "Notify PR creator if vulnerabilities are found"

inputs:
  message:
    description: "Message to post on the PR"
    default: "⚠️ Vulnerabilities detected"
    required: false
  token:
    description: "GitHub token or PAT"
    required: true
  audit-dir:
    description: "Directory containing audit reports"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check for vulnerabilities
      id: check
      shell: bash
      run: |
        count=0
        critical=""
        high=""
        medium=""
        low=""
        unknown=""

        for f in "$AUDIT_DIR"/*.json; do
          if [ -f "$f" ]; then
            c=$(jq '[.dependencies[].vulns[]?] | length' "$f")
            count=$((count + c))

            # Iterate over each vulnerability object from the JSON file
            while IFS= read -r vuln; do
              # Extract the vulnerability ID (GHSA or CVE) and fix versions if available
              id=$(echo "$vuln" | jq -r '.id')
              fix=$(echo "$vuln" | jq -r '.fix_versions | join(", ")')

              # Default values if we can't get severity
              sev="UNKNOWN"
              band="UNKNOWN"

              if [ -n "$id" ]; then
                resp=$(curl -s "https://api.osv.dev/v1/vulns/$id")

                # Get the simple severity band (CRITICAL, HIGH, MEDIUM, LOW)
                band=$(echo "$resp" | jq -r '.database_specific.severity // empty')
                if [ -n "$band" ] && [ "$band" != "null" ]; then
                  sev="$band"
                fi
              fi

              line="- $id (fix: $fix, severity: $sev, band: $band)"

              case "$band" in
                CRITICAL) critical="$critical\n$line" ;;
                HIGH)     high="$high\n$line" ;;
                MEDIUM)   medium="$medium\n$line" ;;
                LOW)      low="$low\n$line" ;;
                UNKNOWN|"") unknown="$unknown\n$line" ;;
              esac
            done < <(jq -c '.dependencies[].vulns[]?' "$f")
          fi
        done

        details=""
        [[ -n "$critical" ]] && details="$details\n**Critical:**$critical\n"
        [[ -n "$high"     ]] && details="$details\n**High:**$high\n"
        [[ -n "$medium"   ]] && details="$details\n**Medium:**$medium\n"
        [[ -n "$low"      ]] && details="$details\n**Low:**$low\n"
        [[ -n "$unknown"  ]] && details="$details\n**Unknown (to be checked):**$unknown"

        echo "count=$count" >> $GITHUB_OUTPUT
        echo "details<<EOF" >> $GITHUB_OUTPUT
        echo -e "$details" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      env:
        AUDIT_DIR: ${{ inputs.audit-dir }}

    - name: Post PR comment
      if: steps.check.outputs.count != '0'
      uses: actions/github-script@v8
      with:
        github-token: ${{ inputs.token }}
        script: |
          const message = process.env.MESSAGE;
          const count = process.env.COUNT;
          const details = process.env.DETAILS;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `${message}: ${count} issues.\n\n${details}\n...\n\n`
          })
      env:
        MESSAGE: ${{ inputs.message }}
        COUNT: ${{ steps.check.outputs.count }}
        DETAILS: ${{ steps.check.outputs.details }}
