name: "Notify"
description: "Notify PR creator if vulnerabilities are found"

inputs:
  message:
    description: "Message to post on the PR"
    default: "⚠️ Python Vulnerabilities detected"
    required: false
  token:
    description: "GitHub token or PAT"
    required: true
  audit-dir:
    description: "Directory containing audit reports"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check for vulnerabilities
      id: check
      shell: bash
      run: |
        count=0
        critical=""
        high=""
        moderate=""
        low=""
        unknown=""

        declare -A seen  # associative array to track unique IDs

        for f in "$AUDIT_DIR"/*.json; do
          if [ -f "$f" ]; then
            while IFS= read -r vuln; do
              id=$(echo "$vuln" | jq -r '.id')
              fix=$(echo "$vuln" | jq -r '.fix_versions | join(", ")')

              # Skip if we've already processed this ID
              if [[ -n "${seen[$id]}" ]]; then
                continue
              fi
              seen[$id]=1
              count=$((count + 1))

              sev="UNKNOWN"
              band="UNKNOWN"
              ghsa=""

              if [ -n "$id" ]; then
                resp=$(curl -s "https://api.osv.dev/v1/vulns/$id")

                # Try severity from database_specific
                band=$(echo "$resp" | jq -r '.database_specific.severity // empty')

                # GHSA alias if present
                ghsa=$(echo "$resp" | jq -r '.aliases[]? | select(startswith("GHSA-"))' | head -n1)

                # If severity missing, try GHSA alias
                if [ -z "$band" ] || [ "$band" == "null" ]; then
                  if [ -n "$ghsa" ]; then
                    ghsa_resp=$(curl -s "https://api.osv.dev/v1/vulns/$ghsa")
                    band=$(echo "$ghsa_resp" | jq -r '.database_specific.severity // empty')
                  fi
                fi

                # Fall back to UNKNOWN if still empty
                if [ -z "$band" ] || [ "$band" == "null" ]; then
                  band="UNKNOWN"
                fi

                sev="$band"
              fi

              # Build line without score
              line="- $id (fix: $fix, severity: $sev${ghsa:+, GHSA: $ghsa})"

              case "$band" in
                CRITICAL) critical="$critical\n$line" ;;
                HIGH)     high="$high\n$line" ;;
                MODERATE) moderate="$moderate\n$line" ;;
                LOW)      low="$low\n$line" ;;
                UNKNOWN|"") unknown="$unknown\n$line" ;;
              esac
            done < <(jq -c '.dependencies[].vulns[]?' "$f")
          fi
        done

        details=""
        [[ -n "$critical" ]] && details="$details\n**Critical:**$critical\n"
        [[ -n "$high"     ]] && details="$details\n**High:**$high\n"
        [[ -n "$moderate" ]] && details="$details\n**Moderate:**$moderate\n"
        [[ -n "$low"      ]] && details="$details\n**Low:**$low\n"
        [[ -n "$unknown"  ]] && details="$details\n**Unknown (to be checked):**$unknown"

        echo "count=$count" >> $GITHUB_OUTPUT
        echo "details<<EOF" >> $GITHUB_OUTPUT
        echo -e "$details" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      env:
        AUDIT_DIR: ${{ inputs.audit-dir }}

    - name: Post PR comment
      if: steps.check.outputs.count != '0'
      uses: actions/github-script@450193c5abd4cdb17ba9f3ffcfe8f635c4bb6c2a
      with:
        github-token: ${{ inputs.token }}
        script: |
          const message = process.env.MESSAGE;
          const count = process.env.COUNT;
          const details = process.env.DETAILS;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `${message}: ${count} unique issues.\n\n${details}\n\n`
          })
      env:
        MESSAGE: ${{ inputs.message }}
        COUNT: ${{ steps.check.outputs.count }}
        DETAILS: ${{ steps.check.outputs.details }}
