-   id: validate-security-scan
    name: Validate the security scan hook
    description: Validate the hook that runs the security scans have ran, and add a signed-off git trailer if all have passed
    language: python # Can this be part of a docker image, with a different entry point?
    entry: validate-security-scan
    stages: [commit-msg]