name: Python Audit
description: Runs pip-audit on requirements.txt and poetry projects

inputs:
  audit-dir:
    description: Directory to store audit reports
    required: true
  python-version:
    description: Python version to use
    required: true

runs:
  using: "composite"
  steps:
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: "${{ inputs.python-version }}"

    - name: "Run Python audit inline"
      shell: bash
      env:
        AUDIT_DIR: ${{ inputs.audit-dir }}
        PIP_AUDIT_VERSION: "2.10.0"
      run: |
        set -e
        REPO_NAME="$(basename "$(realpath .)")"

        # Python: pip-based
        # ToDo: Improve handling of multiple envs (requirements_dev.txt)
        find . -type f -name "requirements*.txt" | while read -r req; do
          # Extracts the directory containing the file
          envdir=$(dirname "$req")
          # Converts the full path of envdir into a relative path from the current working directory
          cleanenv=$(realpath --relative-to=. "$envdir")
          # Use the correct requirements filename in the output name
          reqfile=$(basename "$req" .txt)
          out="$AUDIT_DIR/${reqfile}_${cleanenv//\//_}_${REPO_NAME}.json"

          echo "Found Python environment:"
          echo "  - Directory: $envdir"
          echo "  - Requirements file: $req"
          echo "  - Intended output: $out"

          # Create and activate virtual environment
          python -m venv "$envdir/.venv"
          source "$envdir/.venv/bin/activate"
          pip install --upgrade pip

          # Install dependencies
          if [ -f "$envdir/requirements.lock" ]; then
            echo "requirements.lock found — installing locked deps"
            pip install -r "$envdir/requirements.lock" --quiet --no-cache-dir
          else
            echo "No requirements.lock — installing from $req"
            pip install -r "$req" --quiet --no-cache-dir
          fi

          # Install and run pip-audit pinned to env variable version
          pip install "pip-audit==${PIP_AUDIT_VERSION}" || { echo "❌ Failed to install pip-audit"; deactivate; rm -rf "$envdir/.venv"; continue; }
          pip-audit -o "$out" -f json || true

          # Cleanup
          deactivate
          rm -rf "$envdir/.venv"
          echo "  - venv directory cleaned up."
          echo ""
        done

        # ToDo: Remove excluded directories from search after sparse-checkout is fixed
        find . -name "pyproject.toml" -not -path "./github-standards/*" | while read -r pyproj; do
          envdir=$(dirname "$pyproj")
          cleanenv=$(realpath --relative-to=. "$envdir")
          out="$AUDIT_DIR/pyproject_${cleanenv//\//_}_${REPO_NAME}.json"
          absolute_out="$(realpath "$PWD")/$out"

          echo "Found Python environment:"
          echo "  - Directory: $envdir"
          echo "  - Requirements file: $pyproj"

          (
            cd "$envdir"
            pip install --upgrade pip

            if [ -f "uv.lock" ]; then
              echo "uv.lock found — installing with uv"
              pip install uv
              uv sync

              echo "Installing pip-audit into uv environment"
              uv pip install "pip-audit==${PIP_AUDIT_VERSION}" || { echo "❌ Failed to install pip-audit"; exit 1; }

              echo "Running pip-audit via uv"
              uv run pip-audit -o "$absolute_out" -f json || true
            else
              echo "Installing Poetry in $envdir"
              pip install poetry

              if [ -f "poetry.lock" ]; then
                echo "poetry.lock found — installing locked deps"
                poetry install --no-root --sync
              else
                # ToDo: Consider using `poetry lock` to generate a lock file before install
                echo "No poetry.lock — installing from pyproject.toml"
                if ! poetry install --no-root; then
                  echo "Poetry install failed in $envdir — skipping this environment"
                  continue
                fi
              fi

              echo "Installing pip-audit in Poetry environment"
              poetry run pip install --upgrade pip
              poetry run pip install "pip-audit==${PIP_AUDIT_VERSION}" || { echo "❌ Failed to install pip-audit"; exit 1; }

              echo "Running pip-audit inside Poetry environment"
              poetry run pip-audit -o "$absolute_out" -f json || true
            fi
          )
        done
