name: Upload to S3
description: Uploads audit reports to S3 with timestamped filenames

inputs:
  audit-dir:
    description: Directory containing audit reports
    required: true
  bucket:
    description: Target S3 bucket name
    required: true
  aws-region:
    description: AWS region for S3 upload
    required: false
    default: eu-west-2
  role-to-assume:
    description: IAM role to assume via OIDC
    required: true

runs:
  using: "composite"
  steps:

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: MyFederatedOIDCSessionName
        aws-region: ${{ inputs.aws-region }}

    - name: Generate timestamp
      id: timestamp
      shell: bash
      run: echo "value=$(date -u +'%Y%m%d-%H%M%S')" >> "$GITHUB_OUTPUT"

    - name: Upload audit reports to S3
      shell: bash
      run: |
        for report in "${{ inputs.audit-dir }}"/*.json; do
          base=$(basename "$report")
          ts="${{ steps.timestamp.outputs.value }}"
          aws s3 cp "$report" "s3://${{ inputs.bucket }}/${ts}-${base}"
        done
