name: "Notify"
description: "Notify PR creator if vulnerabilities are found"

inputs:
  message:
    description: "Message to post on the PR"
    required: false
    default: "⚠️ Vulnerabilities detected"
  token:
    description: "GitHub token or PAT"
    required: true
  audit-dir:
    description: "Directory containing audit reports"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check for vulnerabilities
      id: check
      shell: bash
      run: |
        # ls ${{ inputs.audit-dir }}/*.json
        # To count if any dependency has non-empty vulns
        count=0
        for f in "${{ inputs.audit-dir }}"/*.json; do
          if [ -f "$f" ]; then
            # `.dependencies[].vulns` produces a sequence of arrays, flattens all those arrays into one and counts the total elements.
            # Filter out nulls before flattening, `// []` replaces any null with an empty array
            c=$(jq '[.dependencies[].vulns // []] | flatten | length' "$f")
            count=$((count + c))
          fi
        done
        echo "count=$count" >> $GITHUB_OUTPUT


    - name: Post PR comment
      if: steps.check.outputs.count != '0'
      uses: actions/github-script@v8
      with:
        github-token: ${{ inputs.token }}
        script: |
          const runUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `${{ inputs.message }}: ${{ steps.check.outputs.count }} issues.\n\n[View workflow run](${runUrl})`
          })
