name: Docker image build and publish to AWS ECR
on: 
  workflow_dispatch:
    inputs:
      ecr_repo:
        description: The name of the repository the image will be pushed to. 
        type: string
      image_tag:
        description: Tag to apply to images.
        type: string

jobs: 
  
  docker-build-and-push:

    concurrency:
      group: docker-publish-${{ github.ref }}
      cancel-in-progress: false

    permissions:
      contents: read
      id-token: write

    name: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Validate Dockerfile with dockerfile-validator
        if: ${{ hashFiles('Dockerfile') != '' }}
        uses: ghe-actions/dockerfile-validator@12ed0b63096a928bd3db6fc47d482b6f462ab9c6
        with:
          dockerfile: 'Dockerfile'
          lint: 'dockerlint'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@555a8e9ce6a5e366d51c2da432d183bddad135f6
        with:
          role-to-assume: ${{ secrets.oidc_iam_role }}
          aws-region: eu-west-2

      - name: Check that the repository exists
        env:
          ECR_REPOSITORY: ${{ inputs.ecr_repo }}
        run: |
          if [[ -z `aws ecr describe-repositories | jq -r ".repositories.[] | .repositoryName" | grep $ECR_REPOSITORY` ]]; then
          aws ecr create-repository --repository-name $ECR_REPOSITORY
          echo "Repository exists."
          fi

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@d63b14614fe5d7fc5e5e52c523dea4e876816cc4

      - name: Build, tag, and push the image to Amazon ECR
        id: build-and-push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecr_repo }}
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest



