name: Common CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [main, master, dev]

env:
  SIGNED_OFF_MESSAGE: "Signed-off-by: DBT pre-commit check"
  FAILURE_MESSAGE: "Your PR has commits that are missing the Signed-off-by trailer. This is likely due to the pre-commit hook not being configured on your local machince. For help in setting up the pre-commit hooks, follow the instructions at https://github.com/uktrade/github-standards/blob/main/docs/Installation.md"
  # TRUFFLEHOG_VERSION: 3.90.8

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout current repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check if pre-commit hook ran before push
        id: pre-commit-check
        run: |
          git log ${{ github.event.pull_request.head.sha }} --format=%B -1 | git interpret-trailers --parse | grep '${{ env.SIGNED_OFF_MESSAGE }}'
        continue-on-error: true # This is only here while we are testing, it should be removed during the go live process so PRs cannot be merged

      - name: Find failure comment
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: ${{ env.FAILURE_MESSAGE }}
        continue-on-error: true # Here incase this step breaks, which would break all org PRs

      - name: Create or update failure comment
        if: failure() || steps.pre-commit-check.outcome == 'failure'
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ env.FAILURE_MESSAGE }}
          edit-mode: replace
        continue-on-error: true # Here incase this step breaks, which would break all org PRs

      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
        name: Remove pre-commit comment
        if: success() && steps.pre-commit-check.outcome == 'success' && steps.find-comment.outputs.comment-id
        with:
          script: |
            github.rest.issues.deleteComment({
              comment_id: ${{ steps.find-comment.outputs.comment-id }},
              owner: context.repo.owner,
              repo: context.repo.repo
            })
        continue-on-error: true # Here incase this step breaks, which would break all org PRs

  # Disable for now, while trufflehog is going through IRAP
  # verify:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       shell: bash
  #   permissions:
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
  #       with:
  #         fetch-depth: 0

  #     - name: Secret Scanning
  #       uses: trufflesecurity/trufflehog@466da5b0bb161144f6afca9afe5d57975828c410
  #       with:
  #         base: "main"
  #         head: ${{ github.head_ref }}
  #         extra_args: --log-level=5 --results=verified,unknown
  #         version: ${{ env.TRUFFLEHOG_VERSION }}
