name: Docker CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [main, master, dev]

jobs:
  validate:
    name: Validate Dockerfile
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Validate Dockerfile with dockerfile-validator
        if: ${{ hashFiles('Dockerfile') != '' }}
        uses: ghe-actions/dockerfile-validator@12ed0b63096a928bd3db6fc47d482b6f462ab9c6
        with:
          dockerfile: "Dockerfile"
          lint: "hadolint"
