name: Pre release

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push-development-image:
    permissions:
      contents: read
      id-token: write
      packages: write
      attestations: write
    uses: ./.github/workflows/build-and-push-to-ghcr.yml
    with:
      image_tags: development
    secrets: inherit
