name: Prerelease

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-development-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install . --group dev
          pip install setuptools-scm>=9

      - name: Extract development version
        run: |
          echo "HOOKS_VERSION=$( \
            SETUPTOOLS_SCM_PRETEND_METADATA='{distance=1}' \
            python3 -m setuptools_scm \
          )" >> $GITHUB_ENV

      - name: Extract tag metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # type=raw,value=${{ env.HOOKS_VERSION }}
            type=raw,value=development

      - name: Log in to GitHub packages Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            HOOKS_VERSION=${{ env.HOOKS_VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
