name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., 1.2.3)"
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-release-latest-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      packages: write
      attestations: write
      id-token: write

    outputs:
      tag: ${{ steps.version.outputs.tag }}
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0

      - name: Validate we're on main branch
        run: |
          current_branch=$(git branch --show-current)
          if [ "$current_branch" != "main" ]; then
            echo "Error: Must be on main branch"
            exit 1
          fi

      - name: Process version and tag
        id: version
        run: |
          input_version="${{ github.event.inputs.version }}"
          clean_version=${input_version#v}

          # Validate version format
          if ! echo "$clean_version" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "Error: Version must be in format x.x.x (with or without v prefix)"
            exit 1
          fi

          git_tag="v$clean_version"

          # Check if tag already exists
          if git rev-parse "$git_tag" >/dev/null 2>&1; then
            echo "Error: Tag $git_tag already exists"
            exit 1
          fi

          echo "version=$clean_version" >> $GITHUB_OUTPUT
          echo "tag=$git_tag" >> $GITHUB_OUTPUT
          echo "Clean version: $clean_version"
          echo "Git tag: $git_tag"

      - name: Build package
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Log in to GitHub packages Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}

  create-github-release:
    needs: [build-release-latest-image]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Create tag and GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.build-release-latest-image.outputs.tag }}
          name: ${{ needs.build-release-latest-image.outputs.tag }}
          generateReleaseNotes: true
          makeLatest: true
