name: Run security checks # This should be in the org repo once confirmed working
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
