name: Verify hooks # This should be in the org repo once confirmed working
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run verify
        run: |
          docker run ghcr.io/uktrade/dbt-hooks:latest \
            --hook-id=run-security-scan \
            --verbose
        continue-on-error: true # Remove this once all tested
